--TRIGGER PARA AJUSTAR LA FECHA SI ENTREGA ES ANTES, PROTOCOLO AGREGA 7 DIAS
CREATE OR REPLACE TRIGGER AjustarFechaEntrega
BEFORE INSERT OR UPDATE ON SERVICIOTRANSPORTE
FOR EACH ROW
BEGIN
  IF :NEW.FECHAENTREGA < :NEW.FECHAINICIO THEN
    :NEW.FECHAENTREGA := :NEW.FECHAINICIO + 7;
  END IF;
END;


--PROCEDIMIENTO ALMACENADO PARA INSERTAR
CREATE OR REPLACE
PROCEDURE INSERTARSERVICIOTRANSPORTE (
    IDV NUMBER,
    IDEC NUMBER,
    FEINICIO DATE, -- Cambié de VARCHAR a DATE
    FEENTREGA DATE, -- Cambié de VARCHAR a DATE
    PESO NUMBER,
    PORIGEN VARCHAR,
    PDESTINO VARCHAR,
    IDCONDUCTOR NUMBER
) IS
    VMAXST NUMBER;
BEGIN
    -- Usamos NVL para garantizar que si MAX es NULL, se asigna 1
    SELECT NVL(MAX(ST.IDSERVICIOTRANSPORTE), 0) + 1
    INTO VMAXST
    FROM SERVICIOTRANSPORTE ST;

    -- Insertamos en SERVICIOTRANSPORTE especificando las columnas
    INSERT INTO SERVICIOTRANSPORTE (
        IDSERVICIOTRANSPORTE,
        IDVEHICULO,
        IDEMPRESACLIENTE,
        FECHAINICIO,
        FECHAENTREGA,
        PESO,
        ORIGEN,
        DESTINO
    ) VALUES (
        VMAXST,
        IDV,
        IDEC,
        FEINICIO,
        FEENTREGA,
        PESO,
        PORIGEN,
        PDESTINO
    );
    
    -- Insertar en SERVICIO_CONDUCTOR_
    INSERT INTO SERVICIO_CONDUCTOR_ (
        IDSERVICIOTRANSPORTE,
        IDCONDUCTOR,
        OBSERVACION
    ) VALUES (
        VMAXST,
        IDCONDUCTOR,
        'OK'
    );

    -- Hacemos COMMIT para confirmar los cambios
    COMMIT;

END;


--FUNCION CALCULAR DIFERENCIA DE FECHAS
CREATE OR REPLACE FUNCTION TiempoEstimado(p_idservicio NUMBER)
RETURN NUMBER
IS
    v_dias NUMBER;
BEGIN
    SELECT FECHAENTREGA - FECHAINICIO
    INTO v_dias
    FROM SERVICIOTRANSPORTE
    WHERE IDSERVICIOTRANSPORTE = p_idservicio;

    RETURN v_dias;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;



